### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by p-i-** [shunsukeaihara/pysas#1]
This is an exciting project.

But it's hard to make progress without documentation: as far as I can see pysas brings together WORLD and SPTK.

If that's the case, it would be nice to state that clearly at the very beginning, and link to both those projects so one can see what is available by looking into them.

(But does it do something further than this? If so, what?)

I can't actually find any documentation for WORLD.

As an example, when I see `f0, spec_mat, aperiod_mat = world.analyze(signal)` in the iPython example, I'm not sure whether `spec_mat` is the spectral envelope, or simply the spectrum.

Looking through the GitHub repo, I can't find the definition.

```
from inspect import *
getdoc( world.analyze )
getcomments( world.analyze )
# getsourcefile( world.spectral_envelope )
# signature( world.analyze )
```

The last 2 fail here, as it appears to be a 'built-in'.

Using iPython's auto-completion on `world.` reveals `world.spectral_envelope`, which suggests that maybe a separate call is necessary to retrieve the envelope.

But `world.spectral_envelope?` yields:

```
Docstring: @return f0, spectrogram
Type:      builtin_function_or_method
```

...which doesn't tell me anything about how to use it.

**Comment by shunsukeaihara** [comment]
World.analyze returns estimated spectral envelop by World.

Sorry, this project is now under experimental and document is incomplete. I will continue to work on it.

**Comment by p-i-** [comment]
It is a splendid project!

It took me very little time to figure out how to use it -- here is my work: https://gist.github.com/p-i-/6e5ab73820b6368a331a

I am going to offer it to Wikipedia

Many thanks for making this possible!

π

**Comment by p-i-** [comment]
Have you looked into http://conda.pydata.org/docs/ http://conda.pydata.org/docs/ ?
According to the SciPy2015 conference it is the new way to manage Python iPython numpy scipy matplotlib ...
I've just installed it, and it is as they say, everything just works!

Maybe you could add pysas to their repository?
http://conda.pydata.org/docs/get-involved.html http://conda.pydata.org/docs/get-involved.html
I think it would be a welcome addition!

π
